version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitoring
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network
    ports:
      - "8080:8080"

  pinger:
    build: ./pinger
    depends_on:
      - kafka
    networks:
      - app-network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "3000:80"

  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
